/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.Conexion1;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

public class FrmCrearBD1 extends javax.swing.JFrame {

    Conexion1 db = new Conexion1();

    public FrmCrearBD1() {
        setUndecorated(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
        this.setSize(210, 390);
        this.setLocationRelativeTo(null);
        btnCrearBD.setEnabled(false);
        btnCrearTabla.setEnabled(false);
        btnEliminarBD.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConectar = new javax.swing.JButton();
        btnCrearBD = new javax.swing.JButton();
        btnCrearTabla = new javax.swing.JButton();
        btnEliminarBD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnConectar.setText("Conectar a SQLServer");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConectar);
        btnConectar.setBounds(20, 130, 170, 40);

        btnCrearBD.setText("Crear Base de Datos");
        btnCrearBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearBDActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearBD);
        btnCrearBD.setBounds(20, 180, 170, 40);

        btnCrearTabla.setText("Crear Tablas");
        btnCrearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTablaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearTabla);
        btnCrearTabla.setBounds(20, 230, 170, 40);

        btnEliminarBD.setText("Eliminar Base de Datos");
        btnEliminarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBDActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarBD);
        btnEliminarBD.setBounds(20, 280, 170, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/restaurant.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 10, 120, 110);

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(20, 330, 170, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        db.SQLSERVERConnection();
        JOptionPane.showMessageDialog(null, "Conexion Exitosa");
        btnConectar.setEnabled(false);
        btnCrearBD.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnCrearBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearBDActionPerformed
        db.createBD("restaurante10");
        btnCrearBD.setEnabled(false);
        btnCrearTabla.setEnabled(true);
    }//GEN-LAST:event_btnCrearBDActionPerformed

    private void btnCrearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTablaActionPerformed
        db.UseBD();
        db.createTable();
        btnCrearTabla.setEnabled(false);
        btnEliminarBD.setEnabled(true);
    }//GEN-LAST:event_btnCrearTablaActionPerformed

    private void btnEliminarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBDActionPerformed
        db.SQLSERVERConnection();
        db.eliminarBD();// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarBDActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearBD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearBD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearBD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearBD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearBD1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnCrearBD;
    private javax.swing.JButton btnCrearTabla;
    private javax.swing.JButton btnEliminarBD;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
