/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import auxiliares.aux_centrarInf;
import javax.swing.JFrame;


/**
 *
 * @author Edwin CR
 */
public class FrmPrincipal extends javax.swing.JFrame {

    InCliente cliente;
    InRestaurante restaurante;
    InTipoMesa tipoMesa;
    InMesa mesa;
    InTipoPlato TipoPlato;
    InPlato plato;
    InTipoAlmacen TipoAlmacen;
    InAlmacen almacen;
    InIngredientes ingrediente;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MiIngredientesPlato = new javax.swing.JMenu();
        MiCliente = new javax.swing.JMenuItem();
        MiRestaurante = new javax.swing.JMenuItem();
        MiTipoMesa = new javax.swing.JMenuItem();
        MiMesa = new javax.swing.JMenuItem();
        MiReserva = new javax.swing.JMenuItem();
        MiTipoPlato = new javax.swing.JMenuItem();
        MiPlatos = new javax.swing.JMenuItem();
        MiTipoAlmacen = new javax.swing.JMenuItem();
        MiAlmacen = new javax.swing.JMenuItem();
        MiIngredientes = new javax.swing.JMenuItem();
        MiIngredientePlatos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivos");

        jMenuItem1.setText("sss");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        MiIngredientesPlato.setText("Procesos");

        MiCliente.setText("Cliente");
        MiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiClienteActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiCliente);

        MiRestaurante.setText("Restaurante");
        MiRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiRestauranteActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiRestaurante);

        MiTipoMesa.setText("Tipo Mesa");
        MiTipoMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiTipoMesaActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiTipoMesa);

        MiMesa.setText("Mesa");
        MiMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiMesaActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiMesa);

        MiReserva.setText("Reserva");
        MiReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiReservaActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiReserva);

        MiTipoPlato.setText("Tipo Plato");
        MiTipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiTipoPlatoActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiTipoPlato);

        MiPlatos.setText("Platos");
        MiPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiPlatosActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiPlatos);

        MiTipoAlmacen.setText("Tipo Almacen");
        MiTipoAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiTipoAlmacenActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiTipoAlmacen);

        MiAlmacen.setText("Almacen");
        MiAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiAlmacenActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiAlmacen);

        MiIngredientes.setText("Ingredientes");
        MiIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiIngredientesActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiIngredientes);

        MiIngredientePlatos.setText("Ingredientes del Plato");
        MiIngredientePlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiIngredientePlatosActionPerformed(evt);
            }
        });
        MiIngredientesPlato.add(MiIngredientePlatos);

        jMenuBar1.add(MiIngredientesPlato);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiClienteActionPerformed
            
            if(InCliente.estadoVentana==null){
                cliente = new InCliente();
                aux_centrarInf.MostrarYcentrarInf(cliente, panel); 
            }else{
                aux_centrarInf.Mensaje();
            }
       
    }//GEN-LAST:event_MiClienteActionPerformed

    private void MiRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiRestauranteActionPerformed
        if(InRestaurante.estado_inf==null){
            restaurante=new InRestaurante();
            aux_centrarInf.MostrarYcentrarInf(restaurante, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiRestauranteActionPerformed

    private void MiTipoMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiTipoMesaActionPerformed
        if(InTipoMesa.estado_inf==null){
            tipoMesa=new InTipoMesa();
            aux_centrarInf.MostrarYcentrarInf(tipoMesa, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiTipoMesaActionPerformed

    private void MiMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiMesaActionPerformed
        // TODO add your handling code here:
        if(InMesa.estado_inf==null){
            mesa=new InMesa();
            aux_centrarInf.MostrarYcentrarInf(mesa, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiMesaActionPerformed

    private void MiReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiReservaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MiReservaActionPerformed

    private void MiTipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiTipoPlatoActionPerformed
        // TODO add your handling code here:
        if (InTipoPlato.estadoV==null) {
            TipoPlato=new InTipoPlato();
            aux_centrarInf.MostrarYcentrarInf(TipoPlato, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiTipoPlatoActionPerformed

    private void MiPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiPlatosActionPerformed
        // TODO add your handling code here:
        if(InPlato.estadoV==null){
            plato=new InPlato();
            aux_centrarInf.MostrarYcentrarInf(plato, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiPlatosActionPerformed

    private void MiTipoAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiTipoAlmacenActionPerformed
        // TODO add your handling code here:
        if(InTipoAlmacen.estadoV==null){
            TipoAlmacen=new InTipoAlmacen();
            aux_centrarInf.MostrarYcentrarInf(TipoAlmacen, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiTipoAlmacenActionPerformed

    private void MiAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiAlmacenActionPerformed
        // TODO add your handling code here:
        if(InAlmacen.estadoV==null){
            almacen=new InAlmacen();
            aux_centrarInf.MostrarYcentrarInf(almacen, panel);
        }else{
            aux_centrarInf.Mensaje();
        }   
    }//GEN-LAST:event_MiAlmacenActionPerformed

    private void MiIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiIngredientesActionPerformed
        // TODO add your handling code here:
        if (InIngredientes.estadoV==null) {
            ingrediente=new InIngredientes();
            aux_centrarInf.MostrarYcentrarInf(ingrediente, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiIngredientesActionPerformed

    private void MiIngredientePlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiIngredientePlatosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MiIngredientePlatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MiAlmacen;
    public javax.swing.JMenuItem MiCliente;
    private javax.swing.JMenuItem MiIngredientePlatos;
    private javax.swing.JMenuItem MiIngredientes;
    private javax.swing.JMenu MiIngredientesPlato;
    public javax.swing.JMenuItem MiMesa;
    private javax.swing.JMenuItem MiPlatos;
    private javax.swing.JMenuItem MiReserva;
    public javax.swing.JMenuItem MiRestaurante;
    private javax.swing.JMenuItem MiTipoAlmacen;
    public javax.swing.JMenuItem MiTipoMesa;
    private javax.swing.JMenuItem MiTipoPlato;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables
}
