/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import auxiliares.aux_centrarInf;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Edwin CR
 */
public class FrmPrincipal extends javax.swing.JFrame {

    InCliente cliente;
    InRestaurante restaurante;
    InTipoMesa tipoMesa;
    InMesa mesa;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MiCliente = new javax.swing.JMenuItem();
        MiRestaurante = new javax.swing.JMenuItem();
        MiTipoMesa = new javax.swing.JMenuItem();
        MiMesa = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivos");

        jMenuItem1.setText("sss");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");

        MiCliente.setText("Cliente");
        MiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiClienteActionPerformed(evt);
            }
        });
        jMenu2.add(MiCliente);

        MiRestaurante.setText("Restaurante");
        MiRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiRestauranteActionPerformed(evt);
            }
        });
        jMenu2.add(MiRestaurante);

        MiTipoMesa.setText("Tipo Mesa");
        MiTipoMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiTipoMesaActionPerformed(evt);
            }
        });
        jMenu2.add(MiTipoMesa);

        MiMesa.setText("Mesa");
        MiMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiMesaActionPerformed(evt);
            }
        });
        jMenu2.add(MiMesa);

        jMenuItem2.setText("Reserva");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiClienteActionPerformed
            
            if(InCliente.estadoVentana==null){
                cliente = new InCliente();
                aux_centrarInf.MostrarYcentrarInf(cliente, panel); 
            }else{
                aux_centrarInf.Mensaje();
            }
       
    }//GEN-LAST:event_MiClienteActionPerformed

    private void MiRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiRestauranteActionPerformed
        if(InRestaurante.estado_inf==null){
            restaurante=new InRestaurante();
            aux_centrarInf.MostrarYcentrarInf(restaurante, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiRestauranteActionPerformed

    private void MiTipoMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiTipoMesaActionPerformed
        if(InTipoMesa.estado_inf==null){
            tipoMesa=new InTipoMesa();
            aux_centrarInf.MostrarYcentrarInf(tipoMesa, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiTipoMesaActionPerformed

    private void MiMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiMesaActionPerformed
        // TODO add your handling code here:
        if(InMesa.estado_inf==null){
            mesa=new InMesa();
            aux_centrarInf.MostrarYcentrarInf(mesa, panel);
        }else{
            aux_centrarInf.Mensaje();
        }
    }//GEN-LAST:event_MiMesaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem MiCliente;
    public javax.swing.JMenuItem MiMesa;
    public javax.swing.JMenuItem MiRestaurante;
    public javax.swing.JMenuItem MiTipoMesa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables
}
