/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import auxiliares.logica;
import auxiliares.pool_bd;
import javax.swing.JOptionPane;

/**
 *
 * @author Edwin CR
 */
public class FrmPoolBD extends javax.swing.JFrame {

    private pool_bd pool;
    private FrmCrearBD crear;
    private logica log;

    /**
     * Creates new form FrmPoolBD
     */
    public FrmPoolBD() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMysql = new javax.swing.JButton();
        btnSqlServer = new javax.swing.JButton();
        btnPostgre = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(34, 15, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECCIONE UN MOTOR DE BASE DE DATOS");

        btnMysql.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMysql.setForeground(new java.awt.Color(95, 119, 130));
        btnMysql.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mysql.png"))); // NOI18N
        btnMysql.setText("MYSQL");
        btnMysql.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMysql.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMysql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMysqlActionPerformed(evt);
            }
        });

        btnSqlServer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSqlServer.setForeground(new java.awt.Color(100, 87, 48));
        btnSqlServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sqlServer.png"))); // NOI18N
        btnSqlServer.setText("SQL SERVER");
        btnSqlServer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSqlServer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSqlServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqlServerActionPerformed(evt);
            }
        });

        btnPostgre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPostgre.setForeground(new java.awt.Color(2, 119, 189));
        btnPostgre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/POSTGRE.png"))); // NOI18N
        btnPostgre.setText("POSTGRESQL");
        btnPostgre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPostgre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPostgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostgreActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(153, 65, 253));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete Database_50px.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR CONFIGURACION DE LA BASE DE DATOS");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMysql, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPostgre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSqlServer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSqlServer, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnMysql, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPostgre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMysqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMysqlActionPerformed
        // TODO add your handling code here:
        this.seleccion(btnMysql.getText());
    }//GEN-LAST:event_btnMysqlActionPerformed

    private void btnPostgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostgreActionPerformed
        // TODO add your handling code here:
        this.seleccion(btnPostgre.getText());
    }//GEN-LAST:event_btnPostgreActionPerformed

    private void btnSqlServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqlServerActionPerformed
        // TODO add your handling code here:
        this.seleccion(btnSqlServer.getText());
    }//GEN-LAST:event_btnSqlServerActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPoolBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPoolBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPoolBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPoolBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPoolBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMysql;
    private javax.swing.JButton btnPostgre;
    private javax.swing.JButton btnSqlServer;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void seleccion(String dato) {

        int op = JOptionPane.YES_NO_OPTION;
        int res = JOptionPane.showConfirmDialog(null, "Esta seguro en elegir la base de datos " + dato + "?", "CONFIRMACION", op);
        if (res == 0) {
            pool = new pool_bd(dato);
            log = new logica();
            
                log.Guardar(pool);
                crear = new FrmCrearBD();
                crear.setVisible(true);
                this.dispose();
            

        }
    }

    public void Eliminar() {
        int op = JOptionPane.YES_NO_OPTION;
        int res = JOptionPane.showConfirmDialog(null, "ESTA SEGURO EN ELIMINAR LA CONFIGURACION DE LA BASE DE DATOS?\n"
                + "Tenga en cuenta que perdera acceso a la informacion guardada en la actual BD", "CUIDADO", op, JOptionPane.WARNING_MESSAGE);
        if (res == 0) {
            log = new logica();
            log.Eliminar();
        }
    }
    
    
}
