/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import logicaBL.MesaBL;
import logicaBL.RestauranteBL;
import logicaBL.TipoMesaBL;

/**
 *
 * @author Edwin CR
 */
public class InMesa extends javax.swing.JInternalFrame {
    public static String estado_inf;
    private TipoMesaBL tipoMesa;
    private RestauranteBL restaurante;
    private MesaBL mesa;
    /**
     * Creates new form InMesa
     */
    public InMesa() {
        initComponents();
        this.setSize(825, 504);
        estado_inf="x";
        this.ListarComboTipoMesa();
        this.ListarComboRestaurante();
        
    }
    
    public void ListarComboTipoMesa(){
        tipoMesa=new TipoMesaBL();
        tipoMesa.ListarTipoMesa(cbTipoMesa);
    }
    
    public void ListarComboRestaurante(){
        restaurante=new RestauranteBL();
        restaurante.ListarRestaurante(cbRestaurante);
    }
    
    public void Guardar(){
        mesa=new MesaBL();
        mesa.GuardarMesa(txtNumeroMesa.getText(), Integer.parseInt(txtCapacidad.getText()), cbEstado.getSelectedItem().toString(), WIDTH, FRAMEBITS);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtNumeroMesa = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        cbTipoMesa = new javax.swing.JComboBox<>();
        cbRestaurante = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CODIGO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 28, -1, -1));

        jLabel2.setText("NUMERO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 66, -1, -1));

        jLabel3.setText("CAPACIDAD:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 104, -1, -1));

        jLabel4.setText("ESTADO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 142, -1, -1));

        jLabel5.setText("TIPO MESA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 180, -1, -1));

        jLabel6.setText("RESTAURANTE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 218, -1, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 25, 110, -1));
        jPanel1.add(txtNumeroMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 63, 78, -1));
        jPanel1.add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 101, 78, -1));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIBRE", "RESERVADA", "OCUPADA", "PIDIENDO", "EN ESPERA", "SERVIDOS", "CUENTA", "PAGADO" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 139, 164, -1));

        cbTipoMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbTipoMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 177, 135, -1));

        cbRestaurante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 215, 164, -1));

        btnRegistrar.setText("REGISTRAR");
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 261, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 430, 390));

        jLabel7.setText("BUSCAR:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 20));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 150, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        estado_inf=null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbRestaurante;
    private javax.swing.JComboBox<String> cbTipoMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtNumeroMesa;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
